id: AA237A074
title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:56:01.426854
  last_modified_at: 2022-03-01 02:56:01.426861
