id: AA237A074
title: 'Declaration of the Power of Truth: A Prayer to Overcome Invading Forces'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:56:01.432014
  last_modified_at: 2022-03-01 02:56:01.432017
