id: AA237A074
title: The Heart of the Transcendent Perfection of Wisdom
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:56:01.435524
  last_modified_at: 2022-03-01 02:56:01.435527
