id: AA237A074
title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara, the
  Glorious Victor, to Avert the Final War'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:56:01.433562
  last_modified_at: 2022-03-01 02:56:01.433565
