id: AA237A074
title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:56:01.424005
  last_modified_at: 2022-03-01 02:56:01.424013
