id: AA237A074
title: The Ultimate, Natural Dispeller of Obstacles
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:56:01.438943
  last_modified_at: 2022-03-01 02:56:01.438946
